<a href="https://colab.research.google.com/github/sai5s5/sai5s5/blob/main/Yet_another_copy_of_arraysort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from array import *


arr = array('i', [25, 16, 3])
print(arr)


array('i', [25, 16, 3])


In [ ]:
from numpy import *


arr = array ([[25, 31, 3], [5, 19, 28]])
print(arr)


[[25 31  3]
 [ 5 19 28]]


In [ ]:
# importing libraries
import numpy as np

a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)


Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


In [ ]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
